name: ci

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    env:
        IMAGE: borisevich
        IMAGE_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: | 
           avrelian1995/avrelian_1995:${{ env.IMAGE }}-${{ github.sha }}-${{ github.run_number }}
           ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE }}-${{ github.sha }}-${{ github.run_number }}

