#name: ci. project
#
#on:
#  push:
#    tags:
#      - "v*.*"
#
#jobs:
#  docker:
#    env:
#        USER: ${{ github.actor }}
#        IMAGE: ${{ github.repository }}
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v3
#      -
#        name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      -
#        name: Build and push
#        id: push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          tags: |
#           ghcr.io/${{ env.IMAGE }}:latest
#           ghcr.io/${{ env.IMAGE }}:${{ github.ref_name }}
#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2
#        env:
#            SLACK_CHANNEL: 08-docker
#            SLACK_COLOR: ${{ job.status }}
#            SLACK_ICON: https://github.com/rtCamp.png?size=48
#            SLACK_MESSAGE: 'Post Content :rocket:'
#            SLACK_TITLE: 'A new version of the project ${{ env.USER }}-${{ env.IMAGE }} has been released. Tag:{{ github.ref_name }}'
#            SLACK_USERNAME: Artiom Borisevich
#            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#