name: ci. project

on:
  push:
    branches:
      - "dev"

jobs:
  docker:
    env:
        USER: ${{ github.actor }}
        IMAGE: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test if image has not root access inside
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check
        run: |
            docker build --network=host -t spring:1.0.0 .
            docker run -d -p 8095:8080 -t spring:1.0.0
            docker images
            curl --request GET --url http://localhost:8095 >> report.txt

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          path: report.txt   
