name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Set start timestamp
        id: start
        run: |
          $(date +%s)
      - name: KinD Cluster setup
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.16.0"
      - name: Testing
        run: |
          kubectl get nodes
          kubectl version --short
      - name: Calculate duration
        run: |
          duration=$(date +%s) - ${{ steps.start.outputs.timestamp }}
          # Do something with duration, set as output to then use in Slack message

