name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Set start timestamp
        id: step2
        run: echo "test=$(date '+%s')" >> $GITHUB_OUTPUT
      - name: KinD Cluster setup
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.16.0"
      - name: Testing
        id: step1
        run: |
         echo -e "Kubernetes version:\n$(kubectl version --short) \n"Nodes info:$(kubectl get nodes)" >> $GITHUB_OUTPUT 
         echo "The time elapsed is $(($(date '+%s')-${{ steps.step2.outputs.test }})) seconds" >> $GITHUB_OUTPUT
      - name: Calculate duration
        run: |
         echo "The time elapsed is $(($(date '+%s')-${{ steps.step2.outputs.test }})) seconds"
         echo ${{ steps.step1.outputs }}

