name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Set start timestamp
        id: step2
        run: echo "test=$(date '+%s')" >> $GITHUB_OUTPUT
      - name: KinD Cluster setup
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.16.0"
      - name: Testing
        id: step1
        env:
          result_file: result.txt
        run: |
         echo -e "Kubernetes version:\n$(kubectl version --short) \nNodes info:$(kubectl get nodes)" >> ${{ env.result_file }}
         echo "The time elapsed is $(($(date '+%s')-${{ steps.step2.outputs.test }})) seconds" >> ${{ env.result_file }}
         echo "test=${{ env.result_file }}" >> $GITHUB_OUTPUT
