name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_password: ${{ secrets.PROXY_PASSWORD }}
        script: |
          whoami
          echo "Podes info:$(kubectl get pods -A)"
          mkdir -p ~/.kube/ 
          scp /etc/rancher/k3s/k3s.yaml ~/.kube/config
 #         ssh -o ProxyCommand="ssh -W %h:%p -q jump_sa@178.124.206.53" -L 6443:127.0.0.1:6443 root@192.168.203.3 -f -N
    - name: KinD Cluster setup
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.16.0" 
    - name: KinD info
      run: |
          echo "Nodes info:$(kubectl get pods -A)"
