name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Set start timestamp
        id: step2
        run: echo "test=$(date '+%s')" >> $GITHUB_OUTPUT
      - name: KinD Cluster setup
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.16.0"
      - name: KinD info
        id: step1
        env:
          result_file: result.txt
        run: |
         echo -e "test=(Kubernetes version:\n$(kubectl version --short) \nNodes info:$(kubectl get nodes) \nThe time elapsed is $(($(date '+%s')-${{ steps.step2.outputs.test }})) seconds)" >> $GITHUB_OUTPUT
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          path: ${{steps.step2.outputs.test}}
