name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      report: report.txt
    steps:
    - name: executing remote ssh commands using password    
      id: info
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_password: ${{ secrets.PROXY_PASSWORD }}
        envs: ${{ env.report }}
        script: |
          echo "$(kubectl get pods -A)" 
          echo "$(kubectl get pods -A)" >> ${{ env.report }}
    - name: Test
      run: |
        cat ${{ env.report }}


