name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      FOO: report.txt
      crushed: false
    steps:
    - name: executing remote ssh commands using password
      id: info
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_password: ${{ secrets.PROXY_PASSWORD }}
        envs: FOO
        script: |
          echo "$(kubectl get pods -A)">> FOO
          echo "BAR=(kubectl get pods -A)" >> $GITHUB_ENV
    - name: Test
      run: |
        cat $FOO
        cat $BAR
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        path: report.log

