name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.info.outputs.info }}
    env:
      report: report.log
    steps:
    - name: executing remote ssh commands using password
      id: info
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_password: ${{ secrets.PROXY_PASSWORD }}
        script: |
          echo "Podes info:$(kubectl get pods -A)"
          echo "Crushed pods:$(kubectl get pods --all-namespaces --field-selector=status.phase=Running)" > ${{ env.report }}
          echo "info<<EOF" >> $GITHUB_OUTPUT
          Crushed pods:$(kubectl get pods --all-namespaces --field-selector=status.phase=Running)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
    - name: Upload file to slack 
      if: ${{ contains(steps.info.outputs.info, 'Running') }}
      uses: rtCamp/action-slack-notify@v2
      env:
            SLACK_CHANNEL: 08-docker
            SLACK_COLOR: ${{ job.status }}
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: 'Post Content :rocket:'
            SLACK_TITLE: 'ALERT!. REPORT: ${{ env.report }}'
            SLACK_USERNAME: Artiom Borisevich
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
