name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      report: report.txt
      crushed: false
    steps:
    - name: executing remote ssh commands using password
      id: info
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_password: ${{ secrets.PROXY_PASSWORD }}
        script: |
          echo "GITHUB_SHA_SHORT=$(kubectl get pods -A | grep -c 'Running')" echo >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT

