name: remote ssh command
on: 
  schedule:
      - cron: '*/10 * * * *'
  push:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.info.outputs.info }}
    env:
      report: report.txt
    steps:
    - name: Add SSH key and Make SSH tunnel to k8s (special)
      id: info
      run: |
       echo "$(sshpass -p "QwertY_13" ssh -oProxyCommand="sshpass ssh -W %h:%p jump_sa@178.124.206.53" root@192.168.203.3 "kubectl get pods -A")" > file.txt
       cat file.txt
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.info.outputs.info }}

