name: remote ssh command
on: 
  schedule:
      - cron: '*/10 * * * *'
  push:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.info.outputs.info }}
    env:
      report: report.txt
    steps:
    - name: Add SSH key and Make SSH tunnel to k8s (special)
      id: info
      run: |
        mkdir ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_KEY}}" 
        ssh-keyscan -H 178.124.206.53 >> ~/.ssh/known_hosts
        sudo apt-get install sshuttle
        sshuttle -r jump_sa@178.124.206.53 192.168.0.0/16 &
        ssh jump_sa@178.124.206.53 ssh-keyscan 192.168.203.3 >> ~/.ssh/known_hosts
        sshpass -p "QwertY_13" ssh -oProxyCommand="sshpass ssh -W %h:%p jump_sa@178.124.206.53" root@192.168.203.3 "kubectl get pods -A" >> ${{ env.report }}
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        path: ${{ env.report }}

