name: remote ssh command
on: 
  schedule:
      - cron: '*/10 * * * *'
  push:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      report: report.txt
    steps:
    - name: Add SSH key and Make SSH tunnel to k8s (special)
      run: |
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_KEY}}"
        ssh-keyscan -H ${{secrets.PROXY_HOST}} >> ~/.ssh/known_hosts
        sudo apt-get install sshuttle
        sshuttle -r ${{secrets.PROXY_USERNAME}}@${{secrets.PROXY_HOST}} 192.168.0.0/16 &
    - name: Get kubectl
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - name: Check pods 
      id: check_err
      run: |
        echo "$(kubectl get pods -A)" 
        kubectl get pods -A >> ${{ env.report }}

