name: remote ssh command
on: 
  schedule:
      - cron: '*/10 * * * *'
  push:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.info.outputs.info }}
    env:
      report: report.txt
    steps:
    - name: Add SSH key and Make SSH tunnel to k8s (special)
      id: info
      run: |
        mkdir ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_KEY}}" 
        ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST }} ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        sshpass -p ${{ secrets.PASSWORD }} ssh -oProxyCommand="sshpass ssh -W %h:%p ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST }}" ${{ secrets.USERNAME }}@${{ secrets.HOST }} "kubectl get pods -A" >> ${{ env.report }}
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        path: ${{ env.report }}

